name: challenge

on: push

jobs:
  job1:
    name: windows job
    runs-on: windows-latest
    steps:
      - name: step one
        uses: actions/checkout@v2
      - name: step two
        run: date
      - name: step three
        run: cat Readme.md
  job2:
    name: ubuntu job
    runs-on: ubuntu-latest
    steps:
      - name: step one
        uses: actions/checkout@v2
      - name: step two
        run: date
  job3:
    name: macos job
    runs-on: macos-latest
    steps:
      - name: step one
        uses: actions/checkout@v2
      - name: step two
        run: date
  job4:
    name: dependencies job
    needs: [job1, job2, job3]
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
